# Clock signal
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]                                                        
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# USB-UART Interface
set_property PACKAGE_PIN B18 [get_ports rx]                                                
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]                                                
set_property IOSTANDARD LVCMOS33 [get_ports tx]

# Control Buttons
# Center Button for Reset
set_property PACKAGE_PIN U18 [get_ports rst]                                                
set_property IOSTANDARD LVCMOS33 [get_ports rst]
# Top Button for Transmit 
set_property PACKAGE_PIN T18 [get_ports btn]                                                
set_property IOSTANDARD LVCMOS33 [get_ports btn]

# boardip (Switches 0-7)
set_property PACKAGE_PIN V17 [get_ports {boardip[0]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[0]}]
set_property PACKAGE_PIN V16 [get_ports {boardip[1]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[1]}]
set_property PACKAGE_PIN W16 [get_ports {boardip[2]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[2]}]
set_property PACKAGE_PIN W17 [get_ports {boardip[3]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[3]}]
set_property PACKAGE_PIN W15 [get_ports {boardip[4]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[4]}]
set_property PACKAGE_PIN V15 [get_ports {boardip[5]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[5]}]
set_property PACKAGE_PIN W14 [get_ports {boardip[6]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[6]}]
set_property PACKAGE_PIN W13 [get_ports {boardip[7]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {boardip[7]}]

# led (LEDs 0-7)
set_property PACKAGE_PIN U16 [get_ports {led[0]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

# 7-Segment Display Segments (Cathodes)
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

# 7-Segment Display Anodes
set_property PACKAGE_PIN U2 [get_ports {an[0]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]                                        
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]